apiVersion: v2
appVersion: "development"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor cloud costs.
name: cost-analyzer
version: "3.0.0"
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
dependencies:
  - condition: global.grafana.enabled
    name: grafana
    repository: file://./charts/grafana
    version: "~1.17.2"